import { randomId } from '../util'
export const newElement = ({
  type,
  x,
  y,
  strokeColor,
  backgroundColor,
  fillStyle,
  strokeWidth,
  strokeStyle,
  roughness,
  opacity,
  width = 0,
  height = 0,
  angle = 0,
  groupIds = [],
  roundness = null,
  boundElements = null,
  link = null,
  locked,
  ...rest
}) => {
    return  {
    id: randomId(),
    type,
    x,
    y,
    width,
    height,
    angle,
    strokeColor,
    backgroundColor,
    fillStyle,
    strokeWidth,
    strokeStyle,
    roughness,
    opacity,
    groupIds,
    roundness,
    version: rest.version || 1,
    versionNonce: rest.versionNonce ?? 0,
    isDeleted: false,
    boundElements,
    updated: Date.now(),
    link,
    locked,
  };
};
